# Generated by Django 4.1.2 on 2022-10-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(default='User **** created at <django.db.models.fields.DateTimeField>', editable=False, max_length=100)),
                ('name', models.CharField(max_length=255, null=True)),
                ('acronym', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
