# Generated by Django 4.1.2 on 2022-10-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='info',
            field=models.CharField(default='User **** created at <django.db.models.fields.DateTimeField>', max_length=100),
        ),
    ]
