# Generated by Django 4.1.2 on 2022-10-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_university_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='info',
        ),
        migrations.AddField(
            model_name='university',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
