# Generated by Django 4.1.2 on 2022-11-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_remove_university_info_university_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
    ]
