# Generated by Django 4.1.2 on 2022-11-02 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_options'),
        ('university', '0004_alter_university_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university_creator', to='user.user'),
        ),
    ]
