# Generated by Django 4.1.3 on 2022-11-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grants', models.FloatField(default=0.0, null=True)),
                ('subsides', models.FloatField(default=0.0, null=True)),
                ('securities', models.CharField(blank=True, max_length=255, null=True)),
                ('orders', models.CharField(blank=True, max_length=255, null=True)),
                ('donations', models.FloatField(default=0.0, null=True)),
            ],
            options={
                'verbose_name': 'Finance',
                'verbose_name_plural': 'Finances',
            },
        ),
    ]
