# Generated by Django 4.1.3 on 2022-11-04 14:19

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('fktprojects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='project',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_project', to='fktprojects.projectpage'),
        ),
    ]
