# Generated by Django 4.1.2 on 2022-11-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finance',
            options={'verbose_name': 'Finance', 'verbose_name_plural': 'Finances'},
        ),
    ]
