# Generated by Django 4.1.2 on 2022-11-02 13:39

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0017_remove_projectpage_financing_source'),
        ('finance', '0002_alter_finance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='project',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_project', to='fktprojects.projectpage'),
        ),
    ]
