# Generated by Django 4.1.3 on 2022-11-03 20:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('DEFAULT', 'Choose a gender'), ('MALE', 'male'), ('FEMALE', 'female')], default='DEFAULT', max_length=15, null=True)),
                ('phone_number', models.CharField(max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+XXX-XX-XXX-XX-XX', e.g. +375291234567.", regex='^\\+?1?\\d{12,12}$')])),
                ('requested_role', models.CharField(choices=[('DEFAULT', 'Select role'), ('VISITOR', 'visitor'), ('MODERATOR', 'moderator'), ('ADMIN', 'admin')], default='DEFAULT', max_length=9, null=True)),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64, null=True)),
                ('username', models.CharField(max_length=32, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_university', to='university.university')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['username'],
            },
        ),
    ]
