# Generated by Django 4.1.2 on 2022-10-27 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+XXX-XX-XXX-XX-XX', e.g. +375291234567.", regex='^\\+?1?\\d{12,12}$')]),
        ),
    ]
