# Generated by Django 4.1.3 on 2022-11-03 20:03

import core.enums
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.TextField(null=True)),
                ('category', models.CharField(choices=[('DEFAULT', 'Choose a category'), ('INVESTMENT', 'Investment'), ('INNOVATIVE', 'Innovative'), ('SCIENTIFIC_RESEARCH', 'Scientific - research'), ('TEACHING_EDUCATIONAL', 'Teaching - educational'), ('MIXED', 'Mixed')], default='DEFAULT', max_length=22, null=True)),
                ('research_year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=core.enums.current_year, verbose_name='year')),
            ],
            options={
                'verbose_name': 'Abstract',
                'verbose_name_plural': 'Abstracts',
            },
        ),
        migrations.CreateModel(
            name='FKTPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'FKT Project',
                'verbose_name_plural': 'FKT Projects',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('project_title', models.CharField(max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('DEFAULT', 'Select status'), ('PLANNING', 'planning'), ('PROCESSING', 'processing'), ('FINISHED', 'finished')], default='DEFAULT', max_length=10, null=True)),
                ('marker', models.CharField(choices=[('RED', 'red'), ('BLUE', 'blue'), ('GREEN', 'green'), ('BLACK', 'black'), ('GREY', 'grey')], default='RED', max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('heading', models.CharField(max_length=100, null=True)),
                ('project_number', models.IntegerField(null=True)),
                ('project_start_date', models.DateField(blank=True, null=True)),
                ('project_end_date', models.DateField(null=True)),
                ('text', models.TextField(null=True)),
                ('category', models.CharField(choices=[('DEFAULT', 'Choose a category'), ('INVESTMENT', 'Investment'), ('INNOVATIVE', 'Innovative'), ('SCIENTIFIC_RESEARCH', 'Scientific - research'), ('TEACHING_EDUCATIONAL', 'Teaching - educational'), ('MIXED', 'Mixed')], default='DEFAULT', max_length=22, null=True)),
            ],
            options={
                'verbose_name': 'Project Page',
                'verbose_name_plural': 'Project Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('publication_type', models.CharField(choices=[('DEFAULT', 'choose publication type'), ('NEWSPAPER', 'newspaper'), ('BOOK', 'book'), ('ARTICLE', 'article'), ('INTERNET', 'internet')], default='DEFAULT', max_length=22, null=True)),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=core.enums.current_year, verbose_name='year')),
                ('post_title', models.CharField(max_length=255, null=True)),
                ('post_subtitle', models.CharField(max_length=255, null=True)),
                ('publication_date', models.DateTimeField(null=True)),
                ('page_number', models.IntegerField(null=True)),
                ('magazine', models.CharField(max_length=100, null=True)),
                ('publishing_house', models.CharField(max_length=100, null=True)),
                ('book_title', models.CharField(max_length=100, null=True)),
                ('publication_link', models.URLField(null=True)),
                ('abstract', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_abstract', to='fktprojects.abstract')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
        ),
    ]
