# Generated by Django 4.1.2 on 2022-10-27 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0077_alter_revision_user'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FKTPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('status', models.CharField(choices=[('DEFAULT', 'Select status'), ('PLANNING', 'planning'), ('PROCESSING', 'processing'), ('FINISHED', 'finished')], default='DEFAULT', max_length=10, null=True)),
                ('marker', models.CharField(choices=[('RED', 'red'), ('BLUE', 'blue'), ('GREEN', 'green'), ('BLACK', 'black'), ('GREY', 'grey')], default='RED', max_length=5, null=True)),
                ('info', models.CharField(default='User <django.db.models.query_utils.DeferredAttribute object at 0x7f016c4dba00> created at <django.db.models.fields.DateTimeField>', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_user', to='user.user')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
