# Generated by Django 4.1.3 on 2022-11-03 20:03

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fktprojects', '0001_initial'),
        ('user', '0001_initial'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('university', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(related_name='publication_authors', to='user.user'),
        ),
        migrations.AddField(
            model_name='publication',
            name='project',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_project', to='fktprojects.projectpage'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_university', to='university.university'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_user', to='user.user'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='project',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abstract_project', to='fktprojects.projectpage'),
        ),
    ]
