# Generated by Django 4.1.3 on 2022-11-03 20:06

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('fktprojects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='publication_authors', to='user.user'),
        ),
    ]
