# Generated by Django 4.1.3 on 2022-11-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
    ]
