# Generated by Django 4.1.2 on 2022-10-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0005_alter_projectpage_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='info',
            field=models.CharField(default='User <django.db.models.query_utils.DeferredAttribute object at 0x7fcb5feaf3d0> created at <django.db.models.fields.DateTimeField>', max_length=100),
        ),
    ]
