# Generated by Django 4.1.3 on 2022-11-07 13:14

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0005_alter_abstract_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='project',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abstract_project', to='fktprojects.projectpage'),
        ),
    ]
