# Generated by Django 4.1.2 on 2022-10-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0006_alter_projectpage_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='info',
        ),
    ]
