# Generated by Django 4.1.3 on 2022-11-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0006_alter_abstract_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='magazine',
            new_name='magazine_title',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='post_subtitle',
            new_name='publication_subtitle',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='post_title',
            new_name='publication_title',
        ),
        migrations.AddField(
            model_name='publication',
            name='newspaper_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
