# Generated by Django 4.1.3 on 2022-11-08 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0007_rename_magazine_publication_magazine_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abstract_project', to='fktprojects.projectpage'),
        ),
    ]
