# Generated by Django 4.1.2 on 2022-10-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('university', '0003_remove_university_info_university_created_at'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('fktprojects', '0007_remove_projectpage_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='category',
            field=models.CharField(choices=[('Choose a category', 'DEFAULT'), ('Investment', 'INVESTMENT'), ('Innovative', 'INNOVATIVE'), ('Scientific - research', 'SCIENTIFIC_RESEARCH'), ('Teaching - educational', 'TEACHING_EDUCATIONAL'), ('Mixed', 'MIXED')], default='DEFAULT', max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='financing_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_financing_source', to='finance.finance'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='heading',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_number',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='project_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_university', to='university.university'),
        ),
    ]
