# Generated by Django 4.1.2 on 2022-10-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0008_projectpage_category_projectpage_financing_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='project_number',
            field=models.IntegerField(null=True),
        ),
    ]
