# Generated by Django 4.1.2 on 2022-10-27 12:20

import core.enums
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0009_alter_projectpage_project_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('category', models.CharField(choices=[('DEFAULT', 'Choose a category'), ('INVESTMENT', 'Investment'), ('INNOVATIVE', 'Innovative'), ('SCIENTIFIC_RESEARCH', 'Scientific - research'), ('TEACHING_EDUCATIONAL', 'Teaching - educational'), ('MIXED', 'Mixed')], default='DEFAULT', max_length=22, null=True)),
                ('research_year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=core.enums.current_year, verbose_name='year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='category',
            field=models.CharField(choices=[('DEFAULT', 'Choose a category'), ('INVESTMENT', 'Investment'), ('INNOVATIVE', 'Innovative'), ('SCIENTIFIC_RESEARCH', 'Scientific - research'), ('TEACHING_EDUCATIONAL', 'Teaching - educational'), ('MIXED', 'Mixed')], default='DEFAULT', max_length=22, null=True),
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_type', models.CharField(choices=[('DEFAULT', 'choose publication type'), ('NEWSPAPER', 'newspaper'), ('BOOK', 'book'), ('ARTICLE', 'article'), ('INTERNET', 'internet')], default='DEFAULT', max_length=22, null=True)),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=core.enums.current_year, verbose_name='year')),
                ('author', models.CharField(max_length=64, null=True)),
                ('post_title', models.CharField(max_length=255, null=True)),
                ('post_subtitle', models.CharField(max_length=255, null=True)),
                ('publication_date', models.DateTimeField(null=True)),
                ('page_number', models.IntegerField(null=True)),
                ('magazine', models.CharField(max_length=100, null=True)),
                ('publishing_house', models.CharField(max_length=100, null=True)),
                ('book_title', models.CharField(max_length=100, null=True)),
                ('publication_link', models.URLField(null=True)),
                ('abstract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications_abstract', to='fktprojects.abstract')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
