# Generated by Django 4.1.3 on 2022-11-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0009_alter_abstract_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='project_start_date',
            field=models.DateField(null=True),
        ),
    ]
