# Generated by Django 4.1.2 on 2022-11-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0011_publication_projectpage_abstract_delete_publications_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstract',
            options={'verbose_name': 'Abstract', 'verbose_name_plural': 'Abstracts'},
        ),
        migrations.AlterModelOptions(
            name='fktpage',
            options={'verbose_name': 'FKT Project', 'verbose_name_plural': 'FKT Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectpage',
            options={'verbose_name': 'Project Page', 'verbose_name_plural': 'Project Pages'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
    ]
