# Generated by Django 4.1.2 on 2022-11-02 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_options'),
        ('university', '0004_alter_university_options'),
        ('finance', '0002_alter_finance_options'),
        ('fktprojects', '0012_alter_abstract_options_alter_fktpage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='abstract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_abstract', to='fktprojects.abstract'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='category',
            field=models.CharField(blank=True, choices=[('DEFAULT', 'Choose a category'), ('INVESTMENT', 'Investment'), ('INNOVATIVE', 'Innovative'), ('SCIENTIFIC_RESEARCH', 'Scientific - research'), ('TEACHING_EDUCATIONAL', 'Teaching - educational'), ('MIXED', 'Mixed')], default='DEFAULT', max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='financing_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_financing_source', to='finance.finance'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='marker',
            field=models.CharField(blank=True, choices=[('RED', 'red'), ('BLUE', 'blue'), ('GREEN', 'green'), ('BLACK', 'black'), ('GREY', 'grey')], default='RED', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='project_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='project_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='project_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='status',
            field=models.CharField(blank=True, choices=[('DEFAULT', 'Select status'), ('PLANNING', 'planning'), ('PROCESSING', 'processing'), ('FINISHED', 'finished')], default='DEFAULT', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_university', to='university.university'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_user', to='user.user'),
        ),
    ]
