# Generated by Django 4.1.2 on 2022-11-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0014_alter_projectpage_abstract_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='abstract',
        ),
    ]
