# Generated by Django 4.1.2 on 2022-11-02 13:33

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0015_remove_projectpage_abstract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstract',
            name='publication',
        ),
        migrations.AddField(
            model_name='abstract',
            name='project',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abstract_project', to='fktprojects.projectpage'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='abstract',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_abstract', to='fktprojects.abstract'),
        ),
        migrations.AddField(
            model_name='publication',
            name='project',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publication_project', to='fktprojects.projectpage'),
        ),
        migrations.AddField(
            model_name='publication',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
