# Generated by Django 4.1.2 on 2022-11-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0016_remove_abstract_publication_abstract_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='financing_source',
        ),
    ]
